'use strict';
const $=id=>document.getElementById(id);
let state=null,token=sessionStorage.getItem('pi-settings-key')||'',reviewed=null;
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function notice(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);$('message').style.display='block';setTimeout(()=>$('message').style.display='none',7000);}
async function api(path,data){const response=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
function switchPanel(name){document.querySelectorAll('.tab').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===name));const titles={overview:'A home for everything.',storage:'Make room for your data.',apps:'Your server, at your pace.',backup:'Keep a copy. Keep control.',access:'Connected, wherever you are.'};$('title').textContent=titles[name];}
document.querySelectorAll('[data-tab]').forEach(e=>e.addEventListener('click',()=>switchPanel(e.dataset.tab)));document.querySelectorAll('[data-go]').forEach(e=>e.addEventListener('click',()=>switchPanel(e.dataset.go)));
const gib=n=>(Number(n||0)/1024**3).toFixed(1)+' GiB';
function placements(){return Object.fromEntries([...document.querySelectorAll('[data-placement]')].map(e=>[e.dataset.placement,e.value.trim()]));}
function invalidate(){reviewed=null;$('apply').disabled=true;}
function render(){
 $('login').hidden=true;$('content').hidden=false;
 $('summary').replaceChildren();[[state.disks.filter(d=>d.eligible).length,'Mounted storage devices'],[state.apps.length,'Available applications'],[state.installed.length,'Selected to install'],[state.enabled.length,'Selected for startup']].forEach(([count,label])=>{const box=element('div',undefined,'stat');box.append(element('span',label),element('strong',String(count)));$('summary').append(box);});
 $('drives').replaceChildren();state.disks.forEach(d=>{const box=element('article',undefined,'drive');box.append(element('span',d.kind||'UNAVAILABLE','kind'),element('h3',d.mount||'Unmounted drive'),element('p',d.model||d.name),element('p','UUID · '+(d.uuid||'not available')));if(d.eligible){box.append(element('div',gib(d.free_bytes)+' available','capacity'));const bar=element('div',undefined,'bar'),fill=element('i');fill.style.width=Math.max(0,Math.min(100,100*(1-d.free_bytes/d.size)))+'%';bar.append(fill);box.append(bar,element('p',gib(d.size)+' device capacity'));}else box.append(element('p',d.reason));$('drives').append(box);});
 $('placements').replaceChildren();state.placements.forEach(row=>{const tr=element('tr'),name=element('td'),drive=element('td'),dest=element('td');name.append(element('strong',row.id.split('/').slice(-2).join('/')),element('small',row.kind+' · '+row.apps.join(', ')));const input=element('input');input.value=row.current;input.dataset.placement=row.id;input.setAttribute('aria-label',row.id+' destination');input.oninput=invalidate;const select=element('select');select.setAttribute('aria-label',row.id+' device');const eligible=state.disks.filter(d=>d.eligible&&(row.kind==='bulk'||d.kind==='SSD'));eligible.forEach(d=>{const opt=element('option',d.kind+' · '+d.mount);opt.value=d.mount;select.append(opt);});const best=eligible.filter(d=>d.mount==='/'||row.current.startsWith(d.mount+'/')).sort((a,b)=>b.mount.length-a.mount.length)[0];if(best)select.value=best.mount;select.onchange=()=>{const root=select.value==='/'?'/srv/pi-data':select.value+'/PiServer';input.value=root+'/'+row.id.replace(/^\/srv\/docker\//,'').replace(/^\/mnt\//,'');invalidate();};drive.append(select);dest.append(input);tr.append(name,drive,dest);$('placements').append(tr);});
 $('app-grid').replaceChildren();state.apps.forEach(a=>{const box=element('article',undefined,'app');box.dataset.name=a.name;const heading=element('h3',a.name.replaceAll('-',' '));const install=element('input');install.type='checkbox';install.checked=state.installed.includes(a.name);install.dataset.installApp=a.name;install.setAttribute('aria-label','Install '+a.name);const installLabel=element('label','Install');installLabel.prepend(install);const startup=element('input');startup.type='checkbox';startup.checked=state.enabled.includes(a.name);startup.dataset.app=a.name;startup.setAttribute('aria-label','Start '+a.name+' at boot');const startupLabel=element('label','Start at boot');startupLabel.prepend(startup);heading.append(installLabel,startupLabel);box.append(heading,element('small',(a.memory_mib||'?')+' MiB declared app budget'),element('p',a.setup||'Managed by the Pi server package.'));const buttons=element('div',undefined,'actions');['Start','Stop'].forEach(label=>{const b=element('button',label,'secondary');b.disabled=!state.deployed;b.onclick=()=>job('app-'+label.toLowerCase(),{app:a.name});buttons.append(b);});box.append(buttons);if(a.default_enabled===false)box.append(element('span','On demand by default','badge'));$('app-grid').append(box);});
 $('backup-drive').replaceChildren(element('option','Select a separate backup disk'));$('backup-drive').firstChild.value='';state.disks.filter(d=>d.eligible&&d.mount!=='/').forEach(d=>{const opt=element('option',(d.model||d.kind)+' · '+d.mount+' · '+gib(d.free_bytes)+' free');opt.value=d.uuid;$('backup-drive').append(opt);});$('backup-drive').value=state.backup.uuid||'';$('backup-folder').value=state.backup.folder||'pi-server';$('backup-bulk').checked=state.backup.include_bulk!==false;$('backup-daily').checked=state.backup.daily===true;
 invalidate();if(state.demo)notice('Read-only preview. Unlock key: preview-only. Changes run only on your Pi.');
}
async function refresh(){try{state=await api('state');render();if(state.job.running)poll();}catch(e){notice(e.message,true);}}
async function job(action,data={}){try{await api(action,data);$('operation').hidden=false;$('operation-title').textContent=action.replaceAll('-',' ');$('operation-result').textContent='Working… You may leave this tab open.';return poll();}catch(e){notice(e.message,true);return null;}}
let polling=false;async function poll(){if(polling)return;polling=true;try{for(;;){const result=await api('job');$('operation').hidden=false;$('operation-title').textContent=result.name||'Operation';$('operation-result').textContent=result.running?'Working… The server keeps a private operation log.':result.error||JSON.stringify(result.result,null,2);if(!result.running){notice(result.error||'Operation completed',Boolean(result.error));break;}await new Promise(r=>setTimeout(r,2500));}}catch(e){notice(e.message,true);}finally{polling=false;}}
$('login-form').onsubmit=e=>{e.preventDefault();token=$('key').value.trim();sessionStorage.setItem('pi-settings-key',token);refresh();};$('refresh').onclick=refresh;
$('auto').onclick=async()=>{try{const result=await api('auto-select',{});document.querySelectorAll('[data-placement]').forEach(e=>e.value=result.placements[e.dataset.placement]);invalidate();notice('Fresh destinations suggested. Review before applying.');}catch(e){notice(e.message,true);}};
$('review').onclick=async()=>{try{const proposed=placements();const result=await api('layout-plan',{placements:proposed});reviewed=JSON.stringify(proposed);$('plan').hidden=false;$('plan').textContent=JSON.stringify({changes:result.changes,requires_copy:result.requires_copy,note:result.note},null,2);$('apply').disabled=false;}catch(e){invalidate();notice(e.message,true);}};
$('apply').onclick=()=>{const proposed=placements();if(JSON.stringify(proposed)!==reviewed)return notice('Review this layout first.',true);invalidate();job('layout-apply',{placements:proposed,migrate:$('migrate').checked});};
 $('save-apps').onclick=async()=>{const installed=[...document.querySelectorAll('[data-install-app]:checked')].map(e=>e.dataset.installApp);const enabled=[...document.querySelectorAll('[data-app]:checked')].map(e=>e.dataset.app);await job('save-apps',{installed,enabled});await refresh();};
$('search').oninput=()=>document.querySelectorAll('.app').forEach(e=>e.hidden=!e.dataset.name.includes($('search').value.toLowerCase()));
$('save-backup').onclick=()=>job('save-backup',{uuid:$('backup-drive').value,folder:$('backup-folder').value,include_bulk:$('backup-bulk').checked,daily:$('backup-daily').checked});
['backup-plan','backup-create'].forEach(id=>$(id).onclick=()=>job(id));$('backup-verify').onclick=()=>job('backup-verify',{backup:$('snapshot').value});
$('install').onclick=()=>job('install');$('tailscale').onclick=()=>job('tailscale-configure');$('enable-panel').onclick=()=>job('enable-panel');$('finish').onclick=async()=>{try{await api('finish',{});notice('Temporary setup server closed.');}catch(e){notice(e.message,true);}};
if(token)refresh();

